# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='start_time')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='end_time')),
            ],
            options={
                'verbose_name': 'activity_periods',
                'db_table': 'Activity Periods',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='real_name')),
                ('tz', models.CharField(max_length=256, unique=True, verbose_name='tz')),
            ],
            options={
                'verbose_name': 'members',
                'db_table': 'Members',
            },
        ),
        migrations.AddField(
            model_name='activity_periods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='project.Members'),
        ),
    ]
