# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200730_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_periods',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='activity_periods',
            name='end_time',
            field=models.DateTimeField(verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='activity_periods',
            name='start_time',
            field=models.DateTimeField(verbose_name='start_time'),
        ),
    ]
